/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2024-05-08

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stdio.h> // debug
#include "stm32f10x.h"
#include "init.h"
#include "lcd1602.h"
#include "timers.h"
#include "keyapi.h"
#include "sensors.h"
#include "coupletable.h"
#include "deadband.h"
#include "debug.h"
#include "communication.h"
#include "modes.h"

/* Private typedef */
/* Private define  */
#define NULL ((void *)0)
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/* Put all things, that need to be done on start up here
   i.e.: Init()
 */
void StartUp(void)
{
   Init();
   delay_LCD(9000 * LCD_DELAY_MULTIPLYER);
   InitLCD();
   InitSamplesLookUpTable();

   communication.flags.bits.firmware_downloaded = 0;

   coldJuncFilter.numberOfLSBsToIgnore = 5;
   tCoupleFilter.numberOfLSBsToIgnore = 5;
   pressureFilter.numberOfLSBsToIgnore = 5;

   dUsart.instance = USART1;
}

void Handle1KHz(Timers *timers)
{

   if (timers->flags.bits._1khz)
   {
   	timers->flags.bits._1khz = false;

      for (uint8_t i = 0; i < KEYS_AMOUNT; i++)
      {
         if (keyCode < 0)
            keyCode = HandleKey(&keys[i]);

         if (keyCode >= 0)
         	break;
      }
   }
}

void Handle100Hz(Timers *timers)
{
	if (timers->flags.bits._100hz)
	{
		timers->flags.bits._100hz = false;

      switch (modeType)
      {
      case MAIN_MODE:
         HandleMainModes(&mode, &keyCode);
         break;

      case SERVICE_MODE:
         HandleServiceModes(&serviceMode, &keyCode);
         break;

      case SUPPORT_MODE:
         HandleSupportModes(&supportMode, &keyCode);
         break;
      
      default:
         modeType = 0;
         break;
      }
	}
}

void Handle25Hz(Timers *timers)
{
   static uint16_t refreshCntr = 0;
	if (timers->flags.bits._25hz)
	{
		timers->flags.bits._25hz = false;

      if (refreshCntr++ > 5)
      {
         refreshCntr = 0;

         SET_REFRESH_LCD;

         tRoom.convertedValue = CalculateRoomTemperature(tRoom.averageValue, 0);
         tCouple.convertedValue = CalculateTemperature(tCouple.averageValue, 0, 275, 25);
         pressureSens.convertedValue = CalculatePressure(pressureSens.averageValue, pressureSens.convertedValue, 3000, 1000);

         // debug
         char dataBuff[128];

         uint32_t size;
         size = sprintf(dataBuff, "%d\n", (int)keyCode);

         SendData_USART(&dUsart, dataBuff, size);

      }

		/* Start ADC1 injected channels conversion */
		ADC1->CR2 |= ADC_CR2_JSWSTART;
	}
}

void HandleSecond(Timers *timers)
{
   if (timers->flags.bits.second)
   {

   	timers->flags.bits.second = false;
   }
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
   StartUp();

	while (1)
	{
		IWDG_ReloadCounter();

		Handle1KHz(&timers);
		Handle100Hz(&timers);
      Handle25Hz(&timers);
		HandleSecond(&timers);
	}
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}

#ifdef USE_SEE
#ifndef USE_DEFAULT_TIMEOUT_CALLBACK
/**
  * @brief  Basic management of the timeout situation.
  * @param  None.
  * @retval sEE_FAIL.
  */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* Return with error code */
  return sEE_FAIL;
}
#endif
#endif /* USE_SEE */

